version: '3'
services:
  groupware-whitelabel-postgres:
    image: postgres:14
    container_name: '${APP_NAME}_POSTGRES'
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - groupware-whitelabel-network

  groupware-whitelabel-adminer:
    image: adminer
    container_name: '${APP_NAME}_ADMINER'
    ports:
      - '8081:8080'
    networks:
      - groupware-whitelabel-network

  groupware-whitelabel-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: '${APP_NAME}_APP'
    image: app-groupware-whitelabel-dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      POSTGRES_HOST: groupware-whitelabel-postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - groupware-whitelabel-postgres
    networks:
      - groupware-whitelabel-network

networks:
  groupware-whitelabel-network:

volumes:
  pg_data:
